export const NFTs = [
  {
    Id: 1,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/nftimages/logo.jpeg",
    Edition: 371,
    // Stock: 128,
    Title: "Spheron",
    // Price: "$10M",

    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
  {
    Id: 2,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/nftimages/logo2.png",
    Edition: 371,
    // Stock: 128,
    Title: "Samdbox",
    // Price: "$10M",
    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
  {
    Id: 3,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/nftimages/logo3.png",
    Edition: 371,
    // Stock: 128,
    Title: "OpenSea",
    // Price: "$10M",
    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
  {
    Id: 4,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/nftimages/logo5.jpeg",
    Edition: 371,
    // Stock: 128,
    Title: "AAVE",
    // Price: "$10M",
    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
  {
    Id: 5,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/nftimages/logo4.jpeg",
    Edition: 371,
    // Stock: 128,
    Title: "Uniswap",
    // Price: "$10M",
    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
  {
    Id: 6,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/nftimages/logo6.jpeg",
    Edition: 371,
    // Stock: 128,
    Title: "MakerDao",
    // Price: "$10M",
    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
];
