export const NFTs = [
  {
    Id: 1,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/chainlink_images/image5.webp",
    Edition: 371,
    // Stock: 128,
    Title: "Eden Richmond Park",
    // Price: "$10M",

    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
  {
    Id: 2,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/chainlink_images/image6.png",
    Edition: 371,
    // Stock: 128,
    Title: "Merklin Oikyo-Verse",
    // Price: "$10M",
    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
  {
    Id: 3,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/chainlink_images/image9.jpeg",
    Edition: 371,
    // Stock: 128,
    Title: "Meta-Housing-Society",
    // Price: "$10M",
    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
  {
    Id: 4,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/chainlink_images/image11.jpeg",
    Edition: 371,
    // Stock: 128,
    Title: "Telda-Towers",
    // Price: "$10M",
    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
  {
    Id: 5,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/chainlink_images/image12.jpeg",
    Edition: 371,
    // Stock: 128,
    Title: "Infinity",
    // Price: "$10M",
    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
  {
    Id: 6,
    // Badge: "Total Sale: $82,571",
    ImageUrl: "/images/chainlink_images/image13.jpeg",
    Edition: 371,
    // Stock: 128,
    Title: "Daisy-Land",
    // Price: "$10M",
    Avatar: "/images/avatar/",
    // Author: "newk3d",
    Likes: 652,
  },
];
